name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      PIP_ROOT_USER_ACTION: ignore
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python.
        uses:  actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -V
