name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
    - uses: actions/setup-python@v5
      with:
        python-version: |
            3.8
            3.11
            3.12
            3.13
    - run: python -V
